# Generated by Django 6.0.5 on 2026-06-05 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('prices', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('province', models.CharField(choices=[('Cavite', 'Cavite'), ('Laguna', 'Laguna'), ('Batangas', 'Batangas'), ('Rizal', 'Rizal'), ('Quezon', 'Quezon')], db_index=True, max_length=100)),
                ('city_municipality', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('market_type', models.CharField(choices=[('public', 'Public Market'), ('private', 'Private Market'), ('mall', 'Mall / Commercial')], default='public', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['province', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MarketAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=300, unique=True)),
                ('source', models.CharField(choices=[('audit', 'Phase 0 Audit'), ('admin', 'Admin Review'), ('auto', 'Automatic')], default='audit', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='markets.market')),
            ],
            options={
                'verbose_name_plural': 'Market Aliases',
                'indexes': [models.Index(fields=['alias'], name='idx_market_alias_lookup')],
            },
        ),
        migrations.CreateModel(
            name='UnknownEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('market', 'Market'), ('commodity', 'Commodity')], db_index=True, max_length=20)),
                ('raw_name', models.TextField()),
                ('resolution_status', models.CharField(choices=[('unresolved', 'Unresolved'), ('resolved', 'Resolved — mapped to existing record'), ('ignored', 'Ignored — not a real entity'), ('new_record_created', 'New record created')], db_index=True, default='unresolved', max_length=30)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('resolved_to_commodity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_unknowns', to='prices.commodity')),
                ('resolved_to_market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_unknowns', to='markets.market')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unknown_entities', to='ingestion.sourcedocument')),
            ],
            options={
                'verbose_name_plural': 'Unknown Entities',
                'ordering': ['-last_seen'],
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'raw_name'), name='uq_unknown_entity_type_name')],
            },
        ),
    ]
