# Generated by Django 6.0.5 on 2026-05-30 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roman_numeral', models.CharField(blank=True, max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Commodity Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PriceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('period_label', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram (kg)'), ('liter', 'Liter'), ('piece', 'Piece'), ('dozen', 'Dozen'), ('pack', 'Pack'), ('can', 'Can'), ('bundle', 'Bundle')], default='kg', max_length=20)),
                ('standard_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodities', to='prices.commoditycategory')),
            ],
            options={
                'verbose_name_plural': 'Commodities',
                'ordering': ['category__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PriceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('respondent_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('respondent_3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('respondent_4', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('respondent_5', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('average_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('previous_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remark', models.CharField(choices=[('high', 'High'), ('low', 'Low'), ('stable', 'Stable'), ('unavailable', 'Unavailable'), ('seasonal', 'Seasonal')], default='stable', max_length=20)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_entries', to='prices.commodity')),
            ],
        ),
    ]
