# Generated by Django 6.0.5 on 2026-06-05 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
        ('markets', '0001_initial'),
        ('prices', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=300, unique=True)),
                ('source', models.CharField(choices=[('audit', 'Phase 0 Audit'), ('admin', 'Admin Review'), ('auto', 'Automatic')], default='audit', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Commodity Aliases',
            },
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_date', models.DateField(db_index=True)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('average_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prevailing_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_quality', models.CharField(choices=[('verified', 'Verified — all fields parsed cleanly'), ('provisional', 'Provisional — partial data, some fields may be missing')], default='verified', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-survey_date'],
            },
        ),
        migrations.AddField(
            model_name='commoditycategory',
            name='default_unit',
            field=models.CharField(choices=[('kg', 'Kilogram (kg)'), ('liter', 'Liter'), ('piece', 'Piece')], default='kg', help_text='Unit used for all commodities in this category unless overridden.', max_length=20),
        ),
        migrations.AlterField(
            model_name='commoditycategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='commodity',
            constraint=models.UniqueConstraint(fields=('name', 'unit', 'category'), name='uq_commodity_name_unit_category'),
        ),
        migrations.AddField(
            model_name='commodityalias',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='prices.commodity'),
        ),
        migrations.AddField(
            model_name='pricesnapshot',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='price_snapshots', to='prices.commodity'),
        ),
        migrations.AddField(
            model_name='pricesnapshot',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='price_snapshots', to='markets.market'),
        ),
        migrations.AddField(
            model_name='pricesnapshot',
            name='source_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='price_snapshots', to='ingestion.sourcedocument'),
        ),
        migrations.AddIndex(
            model_name='commodityalias',
            index=models.Index(fields=['alias'], name='idx_commodity_alias_lookup'),
        ),
        migrations.AddIndex(
            model_name='pricesnapshot',
            index=models.Index(fields=['-survey_date'], name='idx_snapshot_date'),
        ),
        migrations.AddIndex(
            model_name='pricesnapshot',
            index=models.Index(fields=['market', '-survey_date'], name='idx_snapshot_market_date'),
        ),
        migrations.AddIndex(
            model_name='pricesnapshot',
            index=models.Index(fields=['commodity', '-survey_date'], name='idx_snapshot_commodity_date'),
        ),
        migrations.AddConstraint(
            model_name='pricesnapshot',
            constraint=models.UniqueConstraint(fields=('market', 'commodity', 'survey_date', 'source_document'), name='uq_price_snapshot'),
        ),
    ]
