# Generated by Django 6.0.5 on 2026-05-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('complainant_name', models.CharField(blank=True, max_length=200)),
                ('complainant_contact', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('sanitation', 'Sanitation'), ('overpricing', 'Overpricing'), ('safety', 'Safety Hazard'), ('food_safety', 'Food Safety'), ('permit', 'Permit Violation'), ('display', 'Display Violation'), ('noise', 'Noise/Disturbance'), ('other', 'Other')], default='other', max_length=30)),
                ('subject', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewing', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
