# Generated by Django 5.2.15 on 2026-06-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='admin_notes',
            new_name='resolution_notes',
        ),
        migrations.AddField(
            model_name='complaint',
            name='evidence_file',
            field=models.FileField(blank=True, null=True, upload_to='complaints/'),
        ),
    ]
