# Generated by Django 6.0.5 on 2026-05-30 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sanitation', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sanitationrecord',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanitation_records', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='sanitationsession',
            name='conducted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanitation_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sanitationsession',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanitation_sessions', to='vendors.marketsection'),
        ),
        migrations.AddField(
            model_name='sanitationrecord',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='sanitation.sanitationsession'),
        ),
        migrations.AlterUniqueTogether(
            name='sanitationrecord',
            unique_together={('session', 'vendor', 'check_item')},
        ),
    ]
