# Generated by Django 6.0.5 on 2026-06-06 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='confidence_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='detected_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='extracted_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='raw_ocr_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='replaces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='documents.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='validation_results',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('business_permit', 'Business Permit'), ('sanitation_cert', 'Sanitation Certificate'), ('health_cert', 'Health Certificate'), ('rent_receipt', 'Rent Receipt'), ('tax_clearance', 'Tax Clearance'), ('contract', 'Contract'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('resubmission_required', 'Resubmission Required')], default='pending', max_length=30),
        ),
    ]
