# Generated by Django 5.2.15 on 2026-06-06 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_confidence_score_document_detected_type_and_more'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='classification_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete'), ('processing', 'Processing'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('resubmission_required', 'Resubmission Required')], default='incomplete', max_length=30),
        ),
        migrations.CreateModel(
            name='ComplianceSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('source', models.CharField(choices=[('SYSTEM', 'System'), ('OCR', 'OCR Engine'), ('ADMIN', 'Administrator'), ('VALIDATION', 'Validation Checks')], default='SYSTEM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_signals', to='documents.document')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_signals', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/pages/')),
                ('raw_ocr_text', models.TextField(blank=True)),
                ('page_upload_order', models.IntegerField()),
                ('detected_page_number', models.IntegerField(blank=True, null=True)),
                ('page_detection_confidence', models.FloatField(blank=True, null=True)),
                ('image_quality_score', models.FloatField(blank=True, null=True)),
                ('validation_results', models.JSONField(blank=True, null=True)),
                ('warnings', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='documents.document')),
            ],
            options={
                'ordering': ['page_upload_order'],
            },
        ),
    ]
