# Generated by Django 6.0.5 on 2026-06-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(max_length=255)),
                ('source_url', models.TextField(blank=True, null=True)),
                ('source_type', models.CharField(choices=[('da_website', 'DA CALABARZON Website'), ('manual_upload', 'Manual Upload')], default='da_website', max_length=50)),
                ('publication_date', models.DateField(db_index=True)),
                ('file_path', models.TextField()),
                ('checksum_sha256', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending — not yet processed'), ('PROCESSING', 'Processing — pipeline running'), ('PROCESSED', 'Processed — snapshots written'), ('FAILED', 'Failed — unhandled error'), ('UNSUPPORTED_IMAGE_PDF', 'Unsupported — image-only PDF, no text layer'), ('SKIPPED_UNSUPPORTED_FORMAT', 'Skipped — text extracted but format not supported by current parser (e.g. FORMAT_A)')], db_index=True, default='PENDING', max_length=50)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('extraction_engine', models.CharField(blank=True, default='pypdf', max_length=50)),
                ('pdf_producer', models.CharField(blank=True, help_text='PDF producer software, e.g. Skia/PDF, iLovePDF', max_length=255, null=True)),
                ('pdf_creator', models.CharField(blank=True, help_text='PDF creator application', max_length=255, null=True)),
                ('pdf_version', models.CharField(blank=True, help_text='PDF specification version, e.g. 1.4, 1.7', max_length=20, null=True)),
                ('raw_extracted_text', models.TextField(blank=True, help_text='Raw text as returned by PyPDF before normalization', null=True)),
                ('normalized_text', models.TextField(blank=True, help_text='Text after normalization layer; used by parser', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-publication_date'],
                'indexes': [models.Index(fields=['-publication_date'], name='idx_srcdoc_pub_date'), models.Index(fields=['status'], name='idx_srcdoc_status')],
            },
        ),
    ]
